/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrdersImport } from './routes/orders'
import { Route as HomeImport } from './routes/home'
import { Route as FnbImport } from './routes/fnb'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const OrdersRoute = OrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const FnbRoute = FnbImport.update({
  id: '/fnb',
  path: '/fnb',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/fnb': {
      id: '/fnb'
      path: '/fnb'
      fullPath: '/fnb'
      preLoaderRoute: typeof FnbImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fnb': typeof FnbRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fnb': typeof FnbRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/fnb': typeof FnbRoute
  '/home': typeof HomeRoute
  '/orders': typeof OrdersRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fnb' | '/home' | '/orders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fnb' | '/home' | '/orders'
  id: '__root__' | '/' | '/fnb' | '/home' | '/orders'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FnbRoute: typeof FnbRoute
  HomeRoute: typeof HomeRoute
  OrdersRoute: typeof OrdersRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FnbRoute: FnbRoute,
  HomeRoute: HomeRoute,
  OrdersRoute: OrdersRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/fnb",
        "/home",
        "/orders"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/fnb": {
      "filePath": "fnb.tsx"
    },
    "/home": {
      "filePath": "home.tsx"
    },
    "/orders": {
      "filePath": "orders.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
